config/routes.rb
Rails.application.routes.draw do
  resources :food_items
  get 'contact_us' => 'home#contact_us'
  get 'menu' => 'home#menu'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :name, :price , :section ,presence:true

  def image_url
    if remote_image_url.present?
      remote_image_url
    else
      "http://loremflickr.com/320/240/#{CGI.escape name}"
    end
  end
end

app/models/section.rb
class Section
  def self.all
    %w(Breakfast Lunch Dinner Drink)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :remote_image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def menu
    @food_items = FoodItem.all
    if params[:section]
      @food_items = FoodItem.where section: params[:section]
    else
      @food_items = FoodItem.all
    end
  end

  def contact_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'form-control-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'form-control-label' %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section, class: 'form-control-label' %>
    <%= f.text_field :section, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remote_image_url, class: 'form-control-label' %>
    <%= f.text_field :remote_image_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-stripedstriped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Remote image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-primary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card">
  <div class="card-block">
    <h4 class="card-title" style="text-align:center"><%= @food_item.name %></h4>
  </div>


  <%= image_tag @food_item.image_url %>


  <div class="card-block">
    <p class="card-text" style="text-align:center"><%= @food_item.description %></p>
   </div>
</div>

<%= link_to 'Edit', edit_food_item_path(@food_item), class: 'btn btn-primary' %> |
<%= link_to 'Back', food_items_path, class: 'btn btn-primary' %>

app/views/home/contact_us.html.erb
<h1 style="padding-top: 80px;">
  Where We Are
</h1>

<div class="row">
  <div class="col-xs-3">
    <h3>Address</h3>
    <address>
      93 Nguyễn Du <br>
      Bến Nghé <br>
      Quận 1 <br>
      Hồ Chí Minh <br>
      Việt Nam<br>
    </address>
  </div>
  <div class="col-xs-9">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.448751530796!2d106.69616194997293!3d10.776901262095093!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f38403ccb63%3A0x7cba5eea907eec66!2zOTMgTmd1eeG7hW4gRHUsIELhur9uIE5naMOpLCBRdeG6rW4gMSwgSOG7kyBDaMOtIE1pbmgsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1468150883692" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome To Our Restaurant</h1>
  <p class="lead">Good to hear from you</p>
  <hr class="m-y-2">
  <p class="lead">
     <%= link_to "Menu", menu_path, class: 'btn btn-primary btn-lg'%>
    <%= link_to "Contact Us", contact_us_path, class: 'btn btn-primary btn-lg'%>
  </p>
</div>

app/views/home/menu.html.erb
<h1>
  Menu
</h1>
<% Section.all.each do |section| %>
  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to section, menu_path(section: section), class: 'btn btn-secondary'%>
</div>
<% end %>

<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort by
  </button>
  <div class="dropdown-menu">
       <% Section.all.each do |section| %>
      <%=link_to "#{section} Sort By",menu_path(:sort_param => "name",section: section),class: "dropdown-item"%>
    <%end%>
  </div>
</div>


<% @food_items.each do |food_item| %>
  <div class="card">
  <div class="card-block">
    <h4 class="card-title">  <%= link_to food_item.name, food_item_path(food_item) %></h4>
    <h6 class="card-subtitle text-muted"><%= food_item.description %></h6>
  </div>
  <%= image_tag food_item.image_url %> <br>
    <br>
  <a href="#" class="btn btn-primary">Order Now</a>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoderRestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-dark bg-primary">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
         <%= link_to "Coder Restaurant", root_path, class: 'navbar-brand'%>

    <ul class="nav navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(root_path)%>" >
        <%= link_to "Home", root_path, class: 'nav-link'%>
      </li>
       <li class="nav-item <%= 'active' if current_page?(menu_path)%>">
         <%= link_to "Menu", menu_path, class: 'nav-link'%>
      </li>

      <li class="nav-item <%= 'active' if current_page?(contact_us_path)%>">
         <%= link_to "Contact Us", contact_us_path, class: 'nav-link'%>
      </li>
    </ul>
  </div>
    </nav>


  <div class="container">
      <%= yield %>
  </div>
  </body>
</html>